# Generated by Django 4.2 on 2023-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210522_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Jobs', 'Jobs'), ('Property', 'Property')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('TR', 'Tripura'), ('AP', 'Andhra Pradesh'), ('MP', 'Madhya Pradesh'), ('JH', 'Jharkhand'), ('ML', 'Meghalaya'), ('MN', 'Manipur'), ('TS', 'Telegana'), ('KA', 'Karnataka'), ('CG', 'Chhattisgarh'), ('GJ', 'Gujarat'), ('MI', 'Sikkim'), ('AS', 'Assam'), ('MH', 'Maharashtra'), ('KL', 'Kerala'), ('MZ', 'Mizoram'), ('OD', 'Odisha'), ('UK', 'Uttarakhand'), ('BR', 'Bihar'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('PB', 'Punjab'), ('NL', 'Nagaland'), ('HP', 'Haryana'), ('GA', 'Goa'), ('AR', 'Arunachal Pradesh'), ('UP', 'Uttar Pradesh'), ('TN', 'Tamil Nadu')], max_length=100),
        ),
    ]
