# Generated by Django 4.2 on 2023-04-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Mobiles', 'Mobiles'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Cars', 'Cars'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('WB', 'West Bengal'), ('BR', 'Bihar'), ('GA', 'Goa'), ('HP', 'Haryana'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('GJ', 'Gujarat'), ('AR', 'Arunachal Pradesh'), ('PB', 'Punjab'), ('CG', 'Chhattisgarh'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('JH', 'Jharkhand'), ('MZ', 'Mizoram'), ('TN', 'Tamil Nadu'), ('NL', 'Nagaland'), ('UK', 'Uttarakhand'), ('TS', 'Telegana'), ('AP', 'Andhra Pradesh'), ('OD', 'Odisha'), ('AS', 'Assam'), ('MI', 'Sikkim'), ('RJ', 'Rajasthan'), ('MH', 'Maharashtra'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh')], max_length=100),
        ),
    ]
