# Generated by Django 4.2 on 2023-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MZ', 'Mizoram'), ('ML', 'Meghalaya'), ('RJ', 'Rajasthan'), ('AR', 'Arunachal Pradesh'), ('GA', 'Goa'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('KL', 'Kerala'), ('PB', 'Punjab'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('HP', 'Haryana'), ('AP', 'Andhra Pradesh'), ('UK', 'Uttarakhand'), ('AS', 'Assam'), ('MN', 'Manipur'), ('BR', 'Bihar'), ('MH', 'Maharashtra'), ('GJ', 'Gujarat'), ('OD', 'Odisha'), ('MP', 'Madhya Pradesh'), ('MI', 'Sikkim'), ('TS', 'Telegana'), ('JH', 'Jharkhand'), ('WB', 'West Bengal'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka')], max_length=100),
        ),
    ]
