# Generated by Django 4.2 on 2023-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('GA', 'Goa'), ('HP', 'Haryana'), ('KA', 'Karnataka'), ('MZ', 'Mizoram'), ('MP', 'Madhya Pradesh'), ('RJ', 'Rajasthan'), ('TS', 'Telegana'), ('KL', 'Kerala'), ('AS', 'Assam'), ('JH', 'Jharkhand'), ('CG', 'Chhattisgarh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('MI', 'Sikkim'), ('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('GJ', 'Gujarat'), ('TN', 'Tamil Nadu'), ('PB', 'Punjab'), ('ML', 'Meghalaya'), ('TR', 'Tripura'), ('WB', 'West Bengal'), ('UK', 'Uttarakhand'), ('NL', 'Nagaland'), ('OD', 'Odisha')], max_length=100),
        ),
    ]
