# Generated by Django 4.2 on 2023-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bikes', 'Bikes'), ('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Cars', 'Cars')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('NL', 'Nagaland'), ('MI', 'Sikkim'), ('TS', 'Telegana'), ('KL', 'Kerala'), ('WB', 'West Bengal'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('CG', 'Chhattisgarh'), ('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra'), ('RJ', 'Rajasthan'), ('HP', 'Haryana'), ('AS', 'Assam'), ('PB', 'Punjab'), ('MN', 'Manipur'), ('BR', 'Bihar'), ('KA', 'Karnataka'), ('OD', 'Odisha'), ('MZ', 'Mizoram'), ('AR', 'Arunachal Pradesh'), ('JH', 'Jharkhand')], max_length=100),
        ),
    ]
