# Generated by Django 4.2 on 2023-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Books&Sports', 'Books&Sports'), ('Furniture', 'Furniture'), ('Property', 'Property')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MP', 'Madhya Pradesh'), ('ML', 'Meghalaya'), ('AS', 'Assam'), ('WB', 'West Bengal'), ('HP', 'Haryana'), ('GA', 'Goa'), ('BR', 'Bihar'), ('MH', 'Maharashtra'), ('MI', 'Sikkim'), ('AP', 'Andhra Pradesh'), ('TS', 'Telegana'), ('OD', 'Odisha'), ('CG', 'Chhattisgarh'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('TR', 'Tripura'), ('RJ', 'Rajasthan'), ('UK', 'Uttarakhand'), ('MN', 'Manipur'), ('PB', 'Punjab'), ('NL', 'Nagaland'), ('JH', 'Jharkhand'), ('AR', 'Arunachal Pradesh'), ('GJ', 'Gujarat'), ('KL', 'Kerala'), ('MZ', 'Mizoram')], max_length=100),
        ),
    ]
