# Generated by Django 4.2 on 2023-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Property', 'Property'), ('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports'), ('Mobiles', 'Mobiles'), ('Cars', 'Cars')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AR', 'Arunachal Pradesh'), ('UK', 'Uttarakhand'), ('TS', 'Telegana'), ('OD', 'Odisha'), ('TR', 'Tripura'), ('AS', 'Assam'), ('RJ', 'Rajasthan'), ('AP', 'Andhra Pradesh'), ('MZ', 'Mizoram'), ('GA', 'Goa'), ('UP', 'Uttar Pradesh'), ('ML', 'Meghalaya'), ('BR', 'Bihar'), ('NL', 'Nagaland'), ('HP', 'Haryana'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('MI', 'Sikkim'), ('GJ', 'Gujarat'), ('PB', 'Punjab'), ('KA', 'Karnataka'), ('JH', 'Jharkhand'), ('CG', 'Chhattisgarh'), ('WB', 'West Bengal'), ('MN', 'Manipur'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh')], max_length=100),
        ),
    ]
