# Generated by Django 4.2 on 2023-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Cars', 'Cars'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Property', 'Property'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('RJ', 'Rajasthan'), ('KL', 'Kerala'), ('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('NL', 'Nagaland'), ('PB', 'Punjab'), ('BR', 'Bihar'), ('AS', 'Assam'), ('GJ', 'Gujarat'), ('MI', 'Sikkim'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('MZ', 'Mizoram'), ('MN', 'Manipur'), ('MP', 'Madhya Pradesh'), ('HP', 'Haryana'), ('WB', 'West Bengal'), ('AR', 'Arunachal Pradesh'), ('GA', 'Goa'), ('KA', 'Karnataka'), ('ML', 'Meghalaya'), ('CG', 'Chhattisgarh'), ('TR', 'Tripura'), ('TN', 'Tamil Nadu'), ('OD', 'Odisha')], max_length=100),
        ),
    ]
