# Generated by Django 4.2 on 2023-04-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Books&Sports', 'Books&Sports'), ('Cars', 'Cars')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('WB', 'West Bengal'), ('UK', 'Uttarakhand'), ('TS', 'Telegana'), ('BR', 'Bihar'), ('HP', 'Haryana'), ('AR', 'Arunachal Pradesh'), ('AP', 'Andhra Pradesh'), ('MN', 'Manipur'), ('TN', 'Tamil Nadu'), ('GJ', 'Gujarat'), ('CG', 'Chhattisgarh'), ('MI', 'Sikkim'), ('UP', 'Uttar Pradesh'), ('AS', 'Assam'), ('NL', 'Nagaland'), ('ML', 'Meghalaya'), ('KA', 'Karnataka'), ('JH', 'Jharkhand'), ('GA', 'Goa'), ('MZ', 'Mizoram'), ('PB', 'Punjab'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('TR', 'Tripura')], max_length=100),
        ),
    ]
