# Generated by Django 4.2 on 2023-04-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AS', 'Assam'), ('JH', 'Jharkhand'), ('TR', 'Tripura'), ('MZ', 'Mizoram'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra'), ('KL', 'Kerala'), ('BR', 'Bihar'), ('NL', 'Nagaland'), ('UK', 'Uttarakhand'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('KA', 'Karnataka'), ('GJ', 'Gujarat'), ('MP', 'Madhya Pradesh'), ('UP', 'Uttar Pradesh'), ('GA', 'Goa'), ('MN', 'Manipur'), ('TN', 'Tamil Nadu'), ('TS', 'Telegana'), ('CG', 'Chhattisgarh'), ('ML', 'Meghalaya'), ('HP', 'Haryana'), ('MI', 'Sikkim'), ('AR', 'Arunachal Pradesh')], max_length=100),
        ),
    ]
