# Generated by Django 4.2 on 2023-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Bikes', 'Bikes'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Furniture', 'Furniture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MH', 'Maharashtra'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('GA', 'Goa'), ('KL', 'Kerala'), ('NL', 'Nagaland'), ('WB', 'West Bengal'), ('MP', 'Madhya Pradesh'), ('RJ', 'Rajasthan'), ('CG', 'Chhattisgarh'), ('GJ', 'Gujarat'), ('JH', 'Jharkhand'), ('MN', 'Manipur'), ('MI', 'Sikkim'), ('TS', 'Telegana'), ('AP', 'Andhra Pradesh'), ('PB', 'Punjab'), ('UK', 'Uttarakhand'), ('HP', 'Haryana'), ('BR', 'Bihar'), ('KA', 'Karnataka'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('OD', 'Odisha'), ('UP', 'Uttar Pradesh'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram')], max_length=100),
        ),
    ]
