# Generated by Django 4.2 on 2023-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bikes', 'Bikes'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Property', 'Property'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('WB', 'West Bengal'), ('MP', 'Madhya Pradesh'), ('TR', 'Tripura'), ('JH', 'Jharkhand'), ('GA', 'Goa'), ('MH', 'Maharashtra'), ('MI', 'Sikkim'), ('GJ', 'Gujarat'), ('PB', 'Punjab'), ('NL', 'Nagaland'), ('KA', 'Karnataka'), ('CG', 'Chhattisgarh'), ('MN', 'Manipur'), ('OD', 'Odisha'), ('AR', 'Arunachal Pradesh'), ('MZ', 'Mizoram'), ('AS', 'Assam'), ('TS', 'Telegana'), ('RJ', 'Rajasthan'), ('KL', 'Kerala'), ('BR', 'Bihar'), ('AP', 'Andhra Pradesh'), ('HP', 'Haryana'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand')], max_length=100),
        ),
    ]
