# Generated by Django 4.2 on 2023-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Jobs', 'Jobs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('NL', 'Nagaland'), ('GA', 'Goa'), ('CG', 'Chhattisgarh'), ('MP', 'Madhya Pradesh'), ('BR', 'Bihar'), ('PB', 'Punjab'), ('AP', 'Andhra Pradesh'), ('MN', 'Manipur'), ('TR', 'Tripura'), ('ML', 'Meghalaya'), ('JH', 'Jharkhand'), ('MI', 'Sikkim'), ('UK', 'Uttarakhand'), ('GJ', 'Gujarat'), ('WB', 'West Bengal'), ('AS', 'Assam'), ('TS', 'Telegana'), ('AR', 'Arunachal Pradesh'), ('OD', 'Odisha'), ('HP', 'Haryana'), ('MH', 'Maharashtra'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('RJ', 'Rajasthan'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('MZ', 'Mizoram')], max_length=100),
        ),
    ]
