# Generated by Django 4.2 on 2023-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Property', 'Property'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Books&Sports', 'Books&Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('TN', 'Tamil Nadu'), ('AR', 'Arunachal Pradesh'), ('RJ', 'Rajasthan'), ('NL', 'Nagaland'), ('MI', 'Sikkim'), ('TR', 'Tripura'), ('MH', 'Maharashtra'), ('GJ', 'Gujarat'), ('OD', 'Odisha'), ('GA', 'Goa'), ('AS', 'Assam'), ('MP', 'Madhya Pradesh'), ('AP', 'Andhra Pradesh'), ('TS', 'Telegana'), ('BR', 'Bihar'), ('MN', 'Manipur'), ('MZ', 'Mizoram'), ('KL', 'Kerala'), ('JH', 'Jharkhand'), ('ML', 'Meghalaya'), ('UP', 'Uttar Pradesh'), ('KA', 'Karnataka'), ('HP', 'Haryana'), ('UK', 'Uttarakhand'), ('PB', 'Punjab'), ('CG', 'Chhattisgarh'), ('WB', 'West Bengal')], max_length=100),
        ),
    ]
