# Generated by Django 4.2 on 2023-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Property', 'Property')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AS', 'Assam'), ('MI', 'Sikkim'), ('MN', 'Manipur'), ('MH', 'Maharashtra'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('TR', 'Tripura'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('AR', 'Arunachal Pradesh'), ('UK', 'Uttarakhand'), ('KL', 'Kerala'), ('JH', 'Jharkhand'), ('HP', 'Haryana'), ('PB', 'Punjab'), ('BR', 'Bihar'), ('WB', 'West Bengal'), ('GJ', 'Gujarat'), ('NL', 'Nagaland'), ('MZ', 'Mizoram'), ('GA', 'Goa'), ('AP', 'Andhra Pradesh'), ('UP', 'Uttar Pradesh'), ('TS', 'Telegana'), ('RJ', 'Rajasthan'), ('ML', 'Meghalaya'), ('CG', 'Chhattisgarh')], max_length=100),
        ),
    ]
