# Generated by Django 4.2 on 2023-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra'), ('CG', 'Chhattisgarh'), ('MN', 'Manipur'), ('TS', 'Telegana'), ('HP', 'Haryana'), ('AR', 'Arunachal Pradesh'), ('MP', 'Madhya Pradesh'), ('MZ', 'Mizoram'), ('JH', 'Jharkhand'), ('UK', 'Uttarakhand'), ('BR', 'Bihar'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('GA', 'Goa'), ('PB', 'Punjab'), ('NL', 'Nagaland'), ('MI', 'Sikkim'), ('ML', 'Meghalaya'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('KL', 'Kerala'), ('AS', 'Assam'), ('TR', 'Tripura'), ('OD', 'Odisha'), ('GJ', 'Gujarat')], max_length=100),
        ),
    ]
