# Generated by Django 4.2 on 2023-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Jobs', 'Jobs'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Bikes', 'Bikes'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('TS', 'Telegana'), ('OD', 'Odisha'), ('KL', 'Kerala'), ('RJ', 'Rajasthan'), ('AS', 'Assam'), ('MN', 'Manipur'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('NL', 'Nagaland'), ('AR', 'Arunachal Pradesh'), ('BR', 'Bihar'), ('MZ', 'Mizoram'), ('MH', 'Maharashtra'), ('TR', 'Tripura'), ('AP', 'Andhra Pradesh'), ('MP', 'Madhya Pradesh'), ('PB', 'Punjab'), ('UK', 'Uttarakhand'), ('JH', 'Jharkhand'), ('CG', 'Chhattisgarh'), ('UP', 'Uttar Pradesh'), ('MI', 'Sikkim'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('ML', 'Meghalaya'), ('WB', 'West Bengal'), ('HP', 'Haryana')], max_length=100),
        ),
    ]
