# Generated by Django 4.2 on 2023-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Furniture', 'Furniture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('PB', 'Punjab'), ('GA', 'Goa'), ('MN', 'Manipur'), ('WB', 'West Bengal'), ('TS', 'Telegana'), ('ML', 'Meghalaya'), ('JH', 'Jharkhand'), ('OD', 'Odisha'), ('AR', 'Arunachal Pradesh'), ('RJ', 'Rajasthan'), ('TR', 'Tripura'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('KA', 'Karnataka'), ('MZ', 'Mizoram'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('AP', 'Andhra Pradesh'), ('BR', 'Bihar'), ('MI', 'Sikkim'), ('AS', 'Assam'), ('CG', 'Chhattisgarh'), ('UK', 'Uttarakhand'), ('MP', 'Madhya Pradesh'), ('HP', 'Haryana'), ('NL', 'Nagaland'), ('GJ', 'Gujarat')], max_length=100),
        ),
    ]
