# Generated by Django 4.2 on 2023-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports'), ('Bikes', 'Bikes'), ('Cars', 'Cars'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('KL', 'Kerala'), ('AS', 'Assam'), ('GA', 'Goa'), ('RJ', 'Rajasthan'), ('MI', 'Sikkim'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('HP', 'Haryana'), ('NL', 'Nagaland'), ('PB', 'Punjab'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('BR', 'Bihar'), ('UK', 'Uttarakhand'), ('TS', 'Telegana'), ('GJ', 'Gujarat'), ('CG', 'Chhattisgarh'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('OD', 'Odisha'), ('MP', 'Madhya Pradesh'), ('TR', 'Tripura'), ('MZ', 'Mizoram'), ('MN', 'Manipur'), ('ML', 'Meghalaya')], max_length=100),
        ),
    ]
