# Generated by Django 4.2 on 2023-04-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports'), ('Jobs', 'Jobs'), ('Property', 'Property'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('GJ', 'Gujarat'), ('KL', 'Kerala'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('AS', 'Assam'), ('MH', 'Maharashtra'), ('MI', 'Sikkim'), ('UK', 'Uttarakhand'), ('HP', 'Haryana'), ('TR', 'Tripura'), ('TS', 'Telegana'), ('MN', 'Manipur'), ('WB', 'West Bengal'), ('BR', 'Bihar'), ('AR', 'Arunachal Pradesh'), ('OD', 'Odisha'), ('GA', 'Goa'), ('TN', 'Tamil Nadu'), ('AP', 'Andhra Pradesh'), ('NL', 'Nagaland'), ('JH', 'Jharkhand'), ('PB', 'Punjab'), ('MP', 'Madhya Pradesh'), ('MZ', 'Mizoram'), ('ML', 'Meghalaya')], max_length=100),
        ),
    ]
