# Generated by Django 4.2 on 2023-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MH', 'Maharashtra'), ('HP', 'Haryana'), ('AP', 'Andhra Pradesh'), ('CG', 'Chhattisgarh'), ('KA', 'Karnataka'), ('AS', 'Assam'), ('TN', 'Tamil Nadu'), ('NL', 'Nagaland'), ('PB', 'Punjab'), ('TR', 'Tripura'), ('WB', 'West Bengal'), ('AR', 'Arunachal Pradesh'), ('UP', 'Uttar Pradesh'), ('MI', 'Sikkim'), ('KL', 'Kerala'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('ML', 'Meghalaya'), ('GJ', 'Gujarat'), ('TS', 'Telegana'), ('UK', 'Uttarakhand'), ('GA', 'Goa'), ('BR', 'Bihar'), ('JH', 'Jharkhand'), ('MN', 'Manipur'), ('MZ', 'Mizoram'), ('MP', 'Madhya Pradesh')], max_length=100),
        ),
    ]
