# Generated by Django 4.2 on 2023-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('JH', 'Jharkhand'), ('HP', 'Haryana'), ('MN', 'Manipur'), ('AR', 'Arunachal Pradesh'), ('MZ', 'Mizoram'), ('AS', 'Assam'), ('RJ', 'Rajasthan'), ('ML', 'Meghalaya'), ('GJ', 'Gujarat'), ('NL', 'Nagaland'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('PB', 'Punjab'), ('MP', 'Madhya Pradesh'), ('GA', 'Goa'), ('TS', 'Telegana'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('MI', 'Sikkim'), ('WB', 'West Bengal'), ('BR', 'Bihar'), ('AP', 'Andhra Pradesh'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('CG', 'Chhattisgarh'), ('TR', 'Tripura'), ('OD', 'Odisha')], max_length=100),
        ),
    ]
