# Generated by Django 4.2 on 2023-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MZ', 'Mizoram'), ('RJ', 'Rajasthan'), ('CG', 'Chhattisgarh'), ('NL', 'Nagaland'), ('AP', 'Andhra Pradesh'), ('TR', 'Tripura'), ('MI', 'Sikkim'), ('WB', 'West Bengal'), ('JH', 'Jharkhand'), ('PB', 'Punjab'), ('GJ', 'Gujarat'), ('AR', 'Arunachal Pradesh'), ('GA', 'Goa'), ('OD', 'Odisha'), ('UK', 'Uttarakhand'), ('ML', 'Meghalaya'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('HP', 'Haryana'), ('MN', 'Manipur'), ('TS', 'Telegana'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('TN', 'Tamil Nadu')], max_length=100),
        ),
    ]
