# Generated by Django 4.2 on 2023-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('BR', 'Bihar'), ('AP', 'Andhra Pradesh'), ('MZ', 'Mizoram'), ('PB', 'Punjab'), ('TN', 'Tamil Nadu'), ('MP', 'Madhya Pradesh'), ('UK', 'Uttarakhand'), ('GJ', 'Gujarat'), ('MN', 'Manipur'), ('WB', 'West Bengal'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('UP', 'Uttar Pradesh'), ('ML', 'Meghalaya'), ('AR', 'Arunachal Pradesh'), ('HP', 'Haryana'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('RJ', 'Rajasthan'), ('MH', 'Maharashtra'), ('OD', 'Odisha'), ('KL', 'Kerala'), ('MI', 'Sikkim'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('AS', 'Assam'), ('KA', 'Karnataka')], max_length=100),
        ),
    ]
