# Generated by Django 4.2 on 2023-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('HP', 'Haryana'), ('UK', 'Uttarakhand'), ('PB', 'Punjab'), ('GA', 'Goa'), ('AS', 'Assam'), ('MI', 'Sikkim'), ('CG', 'Chhattisgarh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('MZ', 'Mizoram'), ('TN', 'Tamil Nadu'), ('WB', 'West Bengal'), ('AP', 'Andhra Pradesh'), ('GJ', 'Gujarat'), ('OD', 'Odisha'), ('TR', 'Tripura'), ('KA', 'Karnataka'), ('NL', 'Nagaland'), ('TS', 'Telegana'), ('ML', 'Meghalaya'), ('MP', 'Madhya Pradesh'), ('AR', 'Arunachal Pradesh'), ('UP', 'Uttar Pradesh'), ('JH', 'Jharkhand'), ('RJ', 'Rajasthan'), ('BR', 'Bihar'), ('KL', 'Kerala')], max_length=100),
        ),
    ]
