# Generated by Django 4.2 on 2023-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MP', 'Madhya Pradesh'), ('AS', 'Assam'), ('MN', 'Manipur'), ('BR', 'Bihar'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('TS', 'Telegana'), ('OD', 'Odisha'), ('ML', 'Meghalaya'), ('AR', 'Arunachal Pradesh'), ('WB', 'West Bengal'), ('AP', 'Andhra Pradesh'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('KL', 'Kerala'), ('JH', 'Jharkhand'), ('HP', 'Haryana'), ('MI', 'Sikkim'), ('MZ', 'Mizoram'), ('UK', 'Uttarakhand'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('TN', 'Tamil Nadu'), ('RJ', 'Rajasthan'), ('MH', 'Maharashtra'), ('GJ', 'Gujarat'), ('PB', 'Punjab')], max_length=100),
        ),
    ]
